### ISSUE TITLE
Проблем с обработка на файлове на кирилица

### ISSUE THREAD

**Issue by antitoxic** [governmentbg/opendata#3]
Оригинална грешка: `Job "push_to_datastore" raised an exception`

Опитах се [да force-на parse-ването](https://opendata.government.bg/dataset/poshtenski-kodove/resource_data/0ea6173c-453e-464e-ba74-abfec83d22c2) (иначе казано да "кача в DataStore") на 1 CSV в таблицата на postgre чрез уеб интерфейса на портала и получих:

```
Грешка: CKAN DataStore bad response. Status code: 409 Conflict. At: http://opendata.government.bg/api/3/action/datastore_create. 
HTTP status code: 409 
Response: {"help": "http://opendata.government.bg/api/3/action/help_show?name=datastore_create", "success": false, "error": {"records": ["row \"1\" has extra keys \"\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0... 
Requested URL: http://opendata.government.bg/api/3/action/datastore_create
```

Това е същата грешка, която получаваме по мейл като:

```
Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
  File "/var/www/ckan/virtualenv/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/var/www/ckan/virtualenv/src/datapusher/datapusher/jobs.py", line 387, in push_to_datastore
    records, api_key, ckan_url)
  File "/var/www/ckan/virtualenv/src/datapusher/datapusher/jobs.py", line 203, in send_resource_to_datastore
    check_response(r, url, 'CKAN DataStore')
  File "/var/www/ckan/virtualenv/src/datapusher/datapusher/jobs.py", line 137, in check_response
    request_url=request_url, response=response.text)

HTTPError
```

**Comment by antitoxic** [comment]
Не е от encoding-a . Туко що пробвах с  https://github.com/obshtestvo/opendata/blob/master/tests/postcodesutf8.csv . Отново има грешка. Може би трябва да rebuild-нем цялата Datastore база данни

**Comment by antitoxic** [comment]
btw `file -i <file>` ми върна грешен encoding

**Comment by antitoxic** [comment]
потенциална причина защо CSV-то е реално разделено с точка и запетая:
ref: http://stackoverflow.com/questions/10140999/csv-with-comma-or-semicolon

**Comment by mitio** [comment]
GitHub също се [оплаква, че не е разделено със запетая](https://www.dropbox.com/s/cpjtm3m7jyovkm9/Screenshot%202015-03-31%2020.17.13.png?dl=0), но си мисля, че datapusher-ът би трябвало да се оправя и с `;`. От друга страна, много лесно може да се тества.

Направих още малко [тестови файлове](https://github.com/obshtestvo/opendata/tree/master/tests). Ако искаш/можеш, пробвай и с тях.

**Comment by antitoxic** [comment]
С тестовете до момента смятам че проблема идва от това че в CKAN datastore има таблица за тоя файл но е създадена с по-малко на брой колони, отколкото в момента засича. Още тествам

**Comment by antitoxic** [comment]
omg... изцяло и само зарарди non-ascii-то е.  

Тествах:
- конвертирах от windows-1251 към utf8 с `iconv`: `iconv -f WINDOWS-1251 -t UTF-8 ./Downloads/Post-Codes-2015.csv > postcodesutf8.csv` - не беше това
- header columns да са на 1 ред - не беше това
- със запетайки вместо точка и запетая - не беше това
- нов dataset и нов файл - не беше това

Ползвах файла, който @mitio даде със съдържание на латиница - сработи.

Разочарован съм.

**Comment by mitio** [comment]
Трябва да го дебъгнем по-добре това и да видим дали ще можем да го оправим. Голям проблем е.

**Comment by antitoxic** [comment]
Ето проблема като issue в главното репо на CKAN: https://github.com/ckan/datapusher/issues/69

**Comment by antitoxic** [comment]
@peperon [това](https://github.com/ckan/datapusher/issues/69#issuecomment-146873576) изглежда достса relevant, ако случайно не си го видял.

**Comment by peperon** [comment]
Да, видях го. Като цяло май ще е най-добре да ъпдейтнем до последната версия на `ckan` за по-добри съобщения от `DataStore`.
