### ISSUE TITLE
Миграция към CKAN 2.5.1

### ISSUE THREAD

**Issue by RadoRado** [governmentbg/opendata#42]
Правя отделно issue за самата миграция.

Тя беше задействана от #1, като @mihail-ivanov направи script за това: https://github.com/mihail-ivanov/ckan-install/blob/master/debian/upgrade_2.3_to_2.5.1.sh

Като за промяната е нужно да се сложи в `config.sh` следното:

```
CKAN_REPO_TAG=https://github.com/mihail-ivanov/ckan.git@master
```

**Comment by RadoRado** [comment]
С @antitoxic ударихме следния проблем:

JavaScript преводите на бутоните бяха изчезнали:

![](https://files.gitter.im/governmentbg/opendata/OzFy/blob)

При build–ване на front-end: `$ paster --plugin=ckan front-end-build -c /path/to/config/production.ini`

Излезе следната грешка:

```
(default)opendata:/etc/ckan/default# paster --plugin=ckan front-end-build
compile green.css
compile fuchsia.css
compile maroon.css
compile red.css
compile main.css
Generating pt_PT
Generating ar
Generating ne
Generating lt
Generating km
Generating my
Generating es
Generating ja
Generating sr
Generating ru
Generating uk_UA
Generating sw
Generating en_CA
Generating cs_CZ
Generating en_AU
Generating tr
Generating mn_MN
Generating ko_KR
Generating zh_CN
Generating it
Generating id
Generating en_GB
Generating fr
Generating da_DK
Generating no
Generating fa_IR
Generating eu
Generating hu
Generating sl
Generating lo
Generating sv
Generating ca
Generating sr_Latn
Generating fi
Generating nl
Generating is
Generating hr
Generating ro
Generating sk
Generating pl
Generating de
Generating es_AR
Generating zh_TW
Generating el
Generating sq
Generating vi
Generating bg
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 2130, in command
    cmd.command()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1793, in command
    self.build_js_translations()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1876, in build_js_translations
    create_js(f, l)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 1863, in create_js
    po = polib.pofile(source)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/polib.py", line 138, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/polib.py", line 86, in _pofile_or_mofile
    instance = parser.parse()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/polib.py", line 1383, in parse
    (self.instance.fpath, self.current_line))
IOError: Syntax error in po file /usr/lib/ckan/default/src/ckan/ckan/lib/../i18n/bg/LC_MESSAGES/ckan.po (line 6)
(default)opendata:/etc/ckan/default#
```

Тази грешка се оправя след изпълнението на следните команди, които регенерират съобщенията и техните преводи.

**Командите се изпълняват в инсталанцията на `CKAN`, където се намира `setup.py`**

```
$ python setup.py extract_messages
$ python setup.py update_catalog
$ python setup.py compile_catalog
```

Най вероятно някой български `.po` файл е повреден.

**Comment by RadoRado** [comment]
@mihail-ivanov ако успееш и ти да го reproduce-неш ще е супер :cat:

**Comment by mihail-ivanov** [comment]
Имаше проблем с merge-а на версия 2.5.1. Сега merge-а е наред и този проблем не се появява. Може да изтриеш неработещата версия на ckan и да сложиш последната от тук: https://github.com/mihail-ivanov/ckan

**Comment by mitio** [comment]
След upgrade до последна версия, ако е разрешен проблемът с push към datastore на файлове, трябва да се пусне push към datastore на всички вече качени ресурси и да минат, ако могат, за да може да се ползва API-то на CKAN за манипулация с ресурсите.

**Comment by mitio** [comment]
CKAN е мигриран до 2.5.3.
